src/Entity/Forum.php
<?php

namespace App\Entity;

use App\Repository\ForumRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ForumRepository::class)]
class Forum
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(name: "forum_id")]
    private ?int $forumID = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $nameForum = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $descriptionForum = null;

    #[ORM\OneToMany(targetEntity: Thread::class, mappedBy: 'forum')]
    private Collection $threads;

    public function __construct()
    {
        $this->threads = new ArrayCollection();
    }

    public function getForumID(): ?int
    {
        return $this->forumID;
    }

    public function getNameForum(): ?string
    {
        return $this->nameForum;
    }

    public function setNameForum(?string $nameForum): static
    {
        $this->nameForum = $nameForum;

        return $this;
    }

    public function getDescriptionForum(): ?string
    {
        return $this->descriptionForum;
    }

    public function setDescriptionForum(?string $descriptionForum): static
    {
        $this->descriptionForum = $descriptionForum;

        return $this;
    }

    /**
     * @return Collection<int, Thread>
     */
    public function getThreads(): Collection
    {
        return $this->threads;
    }

    public function addThread(Thread $thread): static
    {
        if (!$this->threads->contains($thread)) {
            $this->threads->add($thread);
            $thread->setForum($this);
        }

        return $this;
    }

    public function removeThread(Thread $thread): static
    {
        if ($this->threads->removeElement($thread)) {
            // set the owning side to null (unless already changed)
            if ($thread->getForum() === $this) {
                $thread->setForum(null);
            }
        }

        return $this;
    }
}

src/Entity/Thread.php
<?php

namespace App\Entity;

use App\Repository\ThreadRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ThreadRepository::class)]
class Thread
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: "AUTO")]
    #[ORM\Column(name: "thread_id", type: "integer")]
    private ?int $threadID = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank]
    #[Assert\Regex('/^[a-zA-Z\s]*$/')]
    private ?string $titleThread = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank]
    #[Assert\DateTime(format: "Y-m-d")]
    private ?string $creationDateThread = null;

    #[ORM\ManyToOne(inversedBy: 'threads')]
    #[ORM\JoinColumn(name: 'forum_id', referencedColumnName: 'forum_id', nullable: false)]
    private ?Forum $forum = null;

    #[ORM\OneToMany(targetEntity: Post::class, mappedBy: 'thread')]
    private Collection $posts;

    #[ORM\ManyToOne(inversedBy: 'threads')]
    #[ORM\JoinColumn(name: 'user_id', referencedColumnName: 'user_id', nullable: false)]
    private ?User $user = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\DateTime(format: "Y-m-d")]
    private ?string $scheduled_publish_time = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $isSpecial = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Published = null;

    public function __construct()
    {
        $this->posts = new ArrayCollection();
    }


    public function getThreadID(): ?int
    {
        return $this->threadID;
    }

    public function getTitleThread(): ?string
    {
        return $this->titleThread;
    }

    public function setTitleThread(?string $titleThread): static
    {
        $this->titleThread = $titleThread;

        return $this;
    }

    public function getCreationDateThread(): ?string
    {
        return $this->creationDateThread;
    }

    public function setCreationDateThread(?string $creationDateThread): static
    {
        $this->creationDateThread = $creationDateThread;

        return $this;
    }

    public function getForum(): ?Forum
    {
        return $this->forum;
    }

    public function setForum(?Forum $forum): static
    {
        $this->forum = $forum;

        return $this;
    }

    /**
     * @return Collection<int, Post>
     */
    public function getPosts(): Collection
    {
        return $this->posts;
    }

    public function addPost(Post $post): static
    {
        if (!$this->posts->contains($post)) {
            $this->posts->add($post);
            $post->setThread($this);
        }

        return $this;
    }

    public function removePost(Post $post): static
    {
        if ($this->posts->removeElement($post)) {
            // set the owning side to null (unless already changed)
            if ($post->getThread() === $this) {
                $post->setThread(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getScheduledPublishTime(): ?string
    {
        return $this->scheduled_publish_time;
    }

    public function setScheduledPublishTime(?string $scheduled_publish_time): static
    {
        $this->scheduled_publish_time = $scheduled_publish_time;

        return $this;
    }

    public function getIsSpecial(): ?string
    {
        return $this->isSpecial;
    }

    public function setIsSpecial(?string $isSpecial): static
    {
        $this->isSpecial = $isSpecial;

        return $this;
    }

    public function getPublished(): ?string
    {
        return $this->Published;
    }

    public function setPublished(?string $Published): static
    {
        $this->Published = $Published;

        return $this;
    }
}

src/Form/ForumType.php
<?php

namespace App\Form;

use App\Entity\Forum;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ForumType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nameForum')
            ->add('descriptionForum')
            ->add('submit', SubmitType::class);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Forum::class,
        ]);
    }
}

src/Controller/ForumController.php
<?php

namespace App\Controller;

use App\Entity\Forum;
use App\Entity\Post;
use App\Entity\Thread;
use App\Entity\User;
use App\Form\ForumType;
use App\Form\PostType;
use App\Form\ScheduledThreadType;
use App\Form\ThreadType;
use App\Repository\ForumRepository;
use App\Repository\PostRepository;
use App\Repository\ThreadRepository;
use App\Service\SmsGenerator;
use Doctrine\Persistence\ManagerRegistry;
use Knp\Component\Pager\PaginatorInterface;
use MercurySeries\FlashyBundle\FlashyNotifier;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormError;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;
use Symfony\Component\Notifier\NotifierInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Validator\ValidatorInterface;
use Symfony\Component\Notifier\Notification\Notification;
use Symfony\Component\Notifier\Recipient\Recipient;
use Symfony\Component\Notifier\ChatterInterface;
use App\Notification\PublishScheduledThreadsNotification;
use Flasher\Prime\FlasherInterface;

class ForumController extends AbstractController
{
    #[Route('/forum', name: 'app_forum')]
    public function index(): Response
    {
        return $this->render('forum/index.html.twig', [
            'controller_name' => 'ForumController',
        ]);
    }

    /**
     * @Route("/forumlist", name="list_forum")
     */
    public function listForums(ForumRepository $repository): Response
    {
        $forums = $repository->findAll();


        return $this->render('forum/forumlist.html.twig', ['forums' => $forums]);
    }

    /**
     * @Route("/threadlist/{forumId}", name="list_thread")
     */
    public function listThreadsByForumId(ThreadRepository $repository, ForumRepository $forumRepository, Request $request): Response
    {
        $forumId = $request->get('forumId');

        $forum = $forumRepository->find($forumId);

        $threads = $repository->findRegularThreadsByForumId($forumId);

        // Check if special threads should be displayed
        if ($forumId == 15) {  //$this->isGranted('ROLE_ADMIN')
            // Fetch scheduled threads to publish
            $scheduledThreads = $repository->findScheduledThreadsToPublish();

            // Merge scheduled threads with regular threads
            $threads = array_merge($threads, $scheduledThreads);
        }

        if ($forum !== null) {
            $forumTitle = $forum->getNameForum();
        } else {
            $forumTitle = '';
        }

        return $this->render('forum/threadlist.html.twig', ['forumTitle' => $forumTitle, 'threads' => $threads]);
    }

    /**
     * @Route("/postlist/{threadId}", name="list_post")
     */
    public function listposts(PostRepository $repository, ThreadRepository $threadRepository, Request $request, PaginatorInterface $paginator): Response
    {
        $threadId = $request->get('threadId');
        $thread = $threadRepository->find($threadId);
        $posts = $repository->findPostsByThreadId($threadId);

        $postsQuery = $repository->findPostsByThreadIdQuery($threadId);
        $pagination = $paginator->paginate(
            $postsQuery,
            $request->query->getInt('page', 1), // Get the page parameter from the request, default to 1
            3 // Items per page
        );

        if ($thread !== null) {
            $threadTitle = $thread->getTitleThread();
        } else {
            $threadTitle = '';
        }



        return $this->render('forum/postlist.html.twig', ['threadTitle' => $threadTitle, 'posts' => $posts, 'threadId' => $threadId, 'pagination' => $pagination]);
    }

    #[Route('/addthreadbyform', name: 'addthreadbyform')]
    public function addthreadbyform(Request $request, ManagerRegistry $managerRegistry, ValidatorInterface $validator, FlashyNotifier $flashy)
    {
        $thread = new Thread();

        $thread->setIsSpecial('no');

        $thread->setPublished('yes');

        $form = $this->createForm(ThreadType::class, $thread);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $managerRegistry->getManager();

            // Retrieve the forumId from the request
            $forumId = $request->request->get('thread')['forum'];

            // Find the Forum entity by its ID
            $forum = $em->getRepository(Forum::class)->find($forumId);

            // Set the forum for the thread
            $thread->setForum($forum);

            $em->persist($thread);
            $em->flush();

            //$flashy->success('Thread created successfully.');
            flash()->addSuccess('"Your thread has been successfully added!"');

            return $this->redirectToRoute("list_thread", ['forumId' => $forumId]);
        }

        // Handle form validation errors
        $errors = [];
        if ($form->isSubmitted()) {
            $violations = $validator->validate($thread);
            foreach ($violations as $violation) {
                $errors[$violation->getPropertyPath()] = $violation->getMessage();
            }
        }

        return $this->render('forum/addThreadByForm.html.twig', [
            'threadForm' => $form->createView(),
            'errors' => $errors,
        ]);
    }

    #[Route('/addpostbyform/{threadId}', name: 'addpostbyform')]
    public function addPostbyform($threadId, Request $request, ManagerRegistry $managerRegistry, ValidatorInterface $validator)
    {
        $post = new Post();
        $form = $this->createForm(PostType::class, $post);

        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            // Validate the form and the date format simultaneously
            if ($form->isValid()) {
                $em = $managerRegistry->getManager();
                $thread = $em->getRepository(Thread::class)->find($threadId);
                $post->setThread($thread);

                $em->persist($post);
                $em->flush();

                flash()->addSuccess('"Your post has been successfully added!"');

                return $this->redirectToRoute("list_post", ['threadId' => $threadId]);
            } else {
                // Validate the date format if the form is submitted but not valid
                $creationDatePost = $form->get('creationDatePost')->getData();

                if (!$this->isValidDateTime($creationDatePost)) {
                    $form->get('creationDatePost')->addError(new FormError('Invalid date format.'));
                }
            }
        }

        return $this->render('forum/addPostByForm.html.twig', [
            'postForm' => $form->createView(),
        ]);
    }
    // Custom method to validate the date format
    private function isValidDateTime(string $dateTime): bool
    {
        $format = 'Y-m-d';
        $dateTimeObject = \DateTime::createFromFormat($format, $dateTime);
        return $dateTimeObject !== false && !array_sum($dateTimeObject::getLastErrors());
    }

    #[Route('/forum/back', name: 'forum_back')]
    public function backOfficeForum(
        ForumRepository $forumRepository,
        ThreadRepository $threadRepository,
        PostRepository $postRepository
    ): Response {
        $forums = $forumRepository->findAll();
        $threads = $threadRepository->findAll();
        $posts = $postRepository->findAll();

        return $this->render('forum/backOfficeForum.html.twig', [
            'forums' => $forums,
            'threads' => $threads,
            'posts' => $posts,
        ]);
    }

    /**
     * @Route("/forum/delete/{forumId}", name="forum_delete")
     */
    public function deleteForum(int $forumId, ManagerRegistry $managerRegistry): Response
    {
        $em = $managerRegistry->getManager();
        $forum = $em->getRepository(Forum::class)->find($forumId);

        if (!$forum) {
            throw $this->createNotFoundException('Forum not found');
        }

        // Delete associated threads
        foreach ($forum->getThreads() as $thread) {
            // Delete associated posts
            foreach ($thread->getPosts() as $post) {
                $em->remove($post);
            }
            $em->remove($thread);
        }

        $em->remove($forum);
        $em->flush();

        return $this->redirectToRoute('forum_back');
    }

    /**
     * @Route("/thread/delete/{threadId}", name="thread_delete")
     */
    public function deleteThread(int $threadId, ManagerRegistry $managerRegistry): Response
    {
        $em = $managerRegistry->getManager();
        $thread = $em->getRepository(Thread::class)->find($threadId);

        if (!$thread) {
            throw $this->createNotFoundException('Thread not found');
        }

        // Delete associated posts
        foreach ($thread->getPosts() as $post) {
            $em->remove($post);
        }

        $em->remove($thread);
        $em->flush();

        return $this->redirectToRoute('forum_back');
    }

    /**
     * @Route("/post/delete/{postId}", name="post_delete")
     */
    public function deletePost(int $postId, ManagerRegistry $managerRegistry): Response
    {
        $em = $managerRegistry->getManager();
        $post = $em->getRepository(Post::class)->find($postId);

        if (!$post) {
            throw $this->createNotFoundException('Post not found');
        }

        $em->remove($post);
        $em->flush();

        return $this->redirectToRoute('forum_back');
    }

    /**
     * @Route("/forum/edit/{forumId}", name="forum_edit")
     */
    public function editForum(Request $request, int $forumId, ManagerRegistry $managerRegistry): Response
    {
        $em = $managerRegistry->getManager();
        $forum = $em->getRepository(Forum::class)->find($forumId);

        if (!$forum) {
            throw $this->createNotFoundException('Forum not found');
        }

templates/forum/addScheduledThreadByForm.html.twig
{% extends 'template/back.html.twig' %}
{% block stylesheets %}

</title>

<meta content="width=device-width, initial-scale=1.0" name="viewport">
<meta content="" name="keywords">
<meta
content="" name="description">

<!-- Favicon -->
<link href="{{ asset('back_office/img/favicon.ico')}}" rel="icon">
<link rel="icon" href="{{ asset('front_office/img/Al3ab/al3ab_blanc.png') }}">

<!-- Bootstrap CSS -->


<!-- Google Web Fonts -->
<link rel="preconnect" href="https://fonts.googleapis.com"> <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link
href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Roboto:wght@500;700&display=swap" rel="stylesheet">

<!-- Icon Font Stylesheet -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
<link
href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

<!-- Libraries Stylesheet -->
<link href="{{ asset('back_office/lib/owlcarousel/assets/owl.carousel.min.css')}}" rel="stylesheet">
<link
href="{{ asset('back_office/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css')}}" rel="stylesheet"/>

<!-- Customized Bootstrap Stylesheet -->
<link
href="{{ asset('back_office/css/bootstrap.min.css')}}" rel="stylesheet">

<!-- Template Stylesheet -->
<link href="{{ asset('back_office/css/style.css')}}" rel="stylesheet">{% endblock %}{% block body %}
{% block sidebar %}
	<!-- Sidebar Start -->
	<div class="sidebar pe-4 pb-3">
		<nav class="navbar bg-secondary navbar-dark">
			<a href="index.html" class="navbar-brand mx-4 mb-3">
				<h3 class="text-primary">
					<i class="fa fa-user-edit me-2"></i>Al3ab</h3>
			</a>
			<div class="d-flex align-items-center ms-4 mb-4">
				<div class="position-relative">
					<img class="rounded-circle" src="{{ asset('back_office/img/user.png')}}" alt="" style="width: 40px; height: 40px;">
					<div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>
				</div>
				<div class="ms-3">
					<h6 class="mb-0">Super Admin</h6>
					<span>Admin</span>
				</div>
			</div>
			<div class="navbar-nav w-100">
				<a href="{{ path('back') }}" class="nav-item nav-link">
					<i class="fa fa-tachometer-alt me-2"></i>Dashboard</a>
				<div class="nav-item dropdown">
					<a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
						<i class="fa fa-laptop me-2"></i>Elements</a>
					<div class="dropdown-menu bg-transparent border-0">
						<a href="button.html" class="dropdown-item">Buttons</a>
						<a href="typography.html" class="dropdown-item">Typography</a>
						<a href="element.html" class="dropdown-item">Other Elements</a>
					</div>
				</div>
				<a href="widget.html" class="nav-item nav-link">
					<i class="fa fa-th me-2"></i>Widgets</a>
				<a href="form.html" class="nav-item nav-link">
					<i class="fa fa-keyboard me-2"></i>Forms</a>
				<a href="{{ path('forum_back') }}" class="nav-item nav-link active">
					<i class="fa fa-table me-2"></i>Forums</a>
				<a href="chart.html" class="nav-item nav-link">
					<i class="fa fa-chart-bar me-2"></i>Charts</a>
				<div class="nav-item dropdown">
					<a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
						<i class="far fa-file-alt me-2"></i>Pages</a>
					<div class="dropdown-menu bg-transparent border-0">
						<a href="signin.html" class="dropdown-item">Sign In</a>
						<a href="signup.html" class="dropdown-item">Sign Up</a>
						<a href="404.html" class="dropdown-item">404 Error</a>
						<a href="blank.html" class="dropdown-item">Blank Page</a>
					</div>
				</div>
			</div>
		</nav>
	</div>
{% endblock %}
{% block content %}
	<div class="content">
		<nav class="navbar navbar-expand bg-secondary navbar-dark sticky-top px-4 py-0">
			<a href="index.html" class="navbar-brand d-flex d-lg-none me-4">
				<h2 class="text-primary mb-0">
					<i class="fa fa-user-edit"></i>
				</h2>
			</a>
			<a href="#" class="sidebar-toggler flex-shrink-0">
				<i class="fa fa-bars"></i>
			</a>
			<form class="d-none d-md-flex ms-4">
				<input class="form-control bg-dark border-0" type="search" placeholder="Search">
			</form>
			<div class="navbar-nav align-items-center ms-auto">
				<div class="nav-item dropdown">
					<a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
						<i class="fa fa-envelope me-lg-2"></i>
						<span class="d-none d-lg-inline-flex">Message</span>
					</a>
					<div class="dropdown-menu dropdown-menu-end bg-secondary border-0 rounded-0 rounded-bottom m-0">
						<a href="#" class="dropdown-item">
							<div class="d-flex align-items-center">
								<img class="rounded-circle" src="{{ asset('back_office/img/user.jpg')}}" alt="" style="width: 40px; height: 40px;">
								<div class="ms-2">
									<h6 class="fw-normal mb-0">Jhon send you a message</h6>
									<small>15 minutes ago</small>
								</div>
							</div>
						</a>
						<hr class="dropdown-divider">
						<a href="#" class="dropdown-item">
							<div class="d-flex align-items-center">
								<img class="rounded-circle" src="img/user.jpg" alt="" style="width: 40px; height: 40px;">
								<div class="ms-2">
									<h6 class="fw-normal mb-0">Jhon send you a message</h6>
									<small>15 minutes ago</small>
								</div>
							</div>
						</a>
						<hr class="dropdown-divider">
						<a href="#" class="dropdown-item">
							<div class="d-flex align-items-center">
								<img class="rounded-circle" src="img/user.jpg" alt="" style="width: 40px; height: 40px;">
								<div class="ms-2">
									<h6 class="fw-normal mb-0">Jhon send you a message</h6>
									<small>15 minutes ago</small>
								</div>
							</div>
						</a>
						<hr class="dropdown-divider">
						<a href="#" class="dropdown-item text-center">See all message</a>
					</div>
				</div>
				<div class="nav-item dropdown">
					<a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
						<i class="fa fa-bell me-lg-2"></i>
						<span class="d-none d-lg-inline-flex">Notificatin</span>
					</a>
					<div class="dropdown-menu dropdown-menu-end bg-secondary border-0 rounded-0 rounded-bottom m-0">
						<a href="#" class="dropdown-item">
							<h6 class="fw-normal mb-0">Profile updated</h6>
							<small>15 minutes ago</small>
						</a>
						<hr class="dropdown-divider">
						<a href="#" class="dropdown-item">
							<h6 class="fw-normal mb-0">New user added</h6>
							<small>15 minutes ago</small>
						</a>
						<hr class="dropdown-divider">
						<a href="#" class="dropdown-item">
							<h6 class="fw-normal mb-0">Password changed</h6>
							<small>15 minutes ago</small>
						</a>
						<hr class="dropdown-divider">
						<a href="#" class="dropdown-item text-center">See all notifications</a>
					</div>
				</div>
				<div class="nav-item dropdown">
					<a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
						<img class="rounded-circle me-lg-2" src="{{ asset('back_office/img/user.png')}}" alt="" style="width: 40px; height: 40px;">
						<span class="d-none d-lg-inline-flex">Super Admin</span>
					</a>
					<div class="dropdown-menu dropdown-menu-end bg-secondary border-0 rounded-0 rounded-bottom m-0">
						<a href="#" class="dropdown-item">My Profile</a>
						<a href="#" class="dropdown-item">Settings</a>
						<a href="#" class="dropdown-item">Log Out</a>
					</div>
				</div>
			</div>
		</nav>
	{% endblock %}

	<!-- Navbar Start -->
	{% block forums %}

		<h1 style="text-align: center; color: #fff;">Add Scheduled Thread</h1>

		{{ form_start(ScheduledThreadForm) }}
		<div style="margin: 0 auto; width: 80%;">
			<div style="margin-bottom: 20px;">
				{{ form_label(ScheduledThreadForm.titleThread, 'Thread Title', {'label_attr': {'style': 'display: block; color: #000;'}}) }}
				{{ form_widget(ScheduledThreadForm.titleThread, {'attr': {'id': 'titleThread', 'style': 'width: 100%; padding: 5px; border: 2px solid #ccc; border-radius: 4px;', 'placeholder': 'Enter thread title'}}) }}
				{% if form_errors(ScheduledThreadForm.titleThread) %}
					<p style="color: red;">{{ form_errors(ScheduledThreadForm.titleThread) }}</p>
				{% endif %}
			</div>
			<div style="margin-bottom: 20px;">
				{{ form_label(ScheduledThreadForm.scheduledPublishTime) }}
				{{ form_widget(ScheduledThreadForm.scheduledPublishTime) }}
			</div>
			<div style="margin-bottom: 20px;">
				{{ form_label(ScheduledThreadForm.creationDateThread) }}
				{{ form_widget(ScheduledThreadForm.creationDateThread) }}
			</div>
			<div style="margin-bottom: 20px;">
				{{ form_label(ScheduledThreadForm.user, 'User', {'label_attr': {'style': 'color: #000; display: block;'}}) }}
				{{ form_widget(ScheduledThreadForm.user, {'attr': {'id': 'user', 'class': 'form-control', 'style': 'width: 100%; padding: 5px; border: 2px solid #ccc; border-radius: 4px;'}}) }}
			</div>

			<div>
				{{ form_widget(ScheduledThreadForm.submit, {'attr': {'style': 'padding: 10px; background-color: red; color: #fff; border: none; border-radius: 4px; cursor: pointer;'}}) }}
			</div>
		</div>
		{{ form_end(ScheduledThreadForm) }}


	{% endblock %}
{% endblock %}

templates/forum/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ForumController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/zmdel/OneDrive/Desktop/3A-PI-Symfony-JavaFx-Template/src/Controller/ForumController.php'|file_link(0) }}">src/Controller/ForumController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/zmdel/OneDrive/Desktop/3A-PI-Symfony-JavaFx-Template/templates/forum/index.html.twig'|file_link(0) }}">templates/forum/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}